config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 105}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user #converting current_user method into a boolean
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)

  end

  def new
    @article = Article.new

  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated scuccessfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path

  end

  private 

  def set_article
  @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end 

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Alpha Blog #{@user.username}, you have successfully singed in."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = "You can only edit your own profile"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-lg mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && article.user == current_user %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, data: { turbo: false }, class: "shadow p-3 mb-3 bg-info rounded gap-6", local: true) do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :description, class: "col-2 col-form=label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group d-flex justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    
      <div class="mb-3 d-flex justify-content-center">
        <%= link_to 'Back to articles listing', articles_path, class: "text-info align-center btn btn-secondary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 text-white">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 text-white">Listing all articles</h1>
<%= will_paginate @articles %>
<%= render 'articles' %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 text-white">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4 text-white"><%= @article.title %></h1>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && @article.user == current_user %>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
          edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Prathik Sridhar</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
    
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <%= link_to "Bloggers", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
              </a>
              <ul class="dropdown-menu">
                <% if logged_in? %>
                  <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
                <% end %>
                <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            
            <% if logged_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile [<%= current_user.username %>]
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %></li>
                  <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                  <li><%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", data: {turbo_method: :delete, turbo_confirm: "Are you Sure?"} %>
                </ul>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', logout_path, class: "nav-link", data: { turbo_method: :delete } %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Log in', login_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', signup_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Aplha Blog 1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">      
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is an About page</h1>

<%= link_to 'Aticles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white rounded d-flex flex-column align-items-center justify-content-center">
    <div class="w-75">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="container">
  <% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
            
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
         
      </button>
      
    </div>
  <% end %>
</div>

  

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, data: { turbo: false }, class: "shadow p-3 mb-3 bg-info rounded gap-6", local: true) do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :email, class: "col-2 col-form=label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :password, class: "col-2 col-form=label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group d-flex justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    
      <div class="mb-3 d-flex justify-content-center">
        <%= link_to 'Back to articles listing', articles_path, class: "text-info align-center btn btn-secondary btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html copy.erb
<h1 class="text-center mt-4 text-white">Alpha Bloggers</h1>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 text-white">Edit your Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-lg mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? && user == current_user %>
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4 text-white">Sign up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4 text-white"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 150 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
  <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4 text-white">Articles</h3>

<%= render 'articles/articles' %>